services:
  platform_webapi_development:
    image: phamdat2002/platform_webapi_dev:latest
    container_name: platform_webapi_dev
    ports:
      - "5004:80"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - mssql_default
      - redis-net

networks:
  redis-net:
    external: true
  mssql_default:
    external: true
