services:
  joytime-development-backend:
    image: consortio/joytime-web-api:latest
    container_name: joytime-web-api
    ports:
      - "4002:80"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - test_default
      - redis-net
    volumes:
      - /data/joytime/api/wwwroot:/app/wwwroot
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4002"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  redis-net:
    external: true
  test_default:
    external: true
