version: "3"
services:
  app:
    image: platform-v2-webapi:latest
    container_name: platform-v2-webapi
    ports:
      - "5006:80"
    depends_on:
      - redis

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
