version: "3"
services:
  app:
    image: phamdat2002/platform-v2-cms:latest
    container_name: platform-v2-cms
    ports:
      - "5007:80"
    depends_on:
      - redis

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
