export default Object.freeze({
    SYSTEM_USER: "SYSTEM.USER",
    SYSTEM_ROLE: "SYSTEM.ROLE",
    ARTICLE: "ARTICLE",
    CONFIG_LIST: "CONFIG.LIST",
    CONFIG_ZONE: "CONFIG.ZONE",
    PRODUCT_LIST: "PRODUCT.LIST",
    PRODUCT_MANUFACTURERS: "PRODUCT.MANUFACTURERS",
    PRODUCT_PRODUCTSPECIFICATIONTEMPLATE: "PRODUCT.PRODUCTSPECIFICATIONTEMPLATE",
    PRODUCT_PROMOTION: "PRODUCT.PROMOTION",
    PRODUCT_PROPERTY: "PRODUCT.PROPERTY",
    PRODUCT_REGION: "PRODUCT.REGION"

})
